### ISSUE TITLE
RootURL

### ISSUE THREAD

**Issue by driesj** [SonarSource/atlasboard-sonarqube-package#1]
hi
I have a problem. I can't connect to my sonar.
my error I counter with:
```
 15:10:07.30 <error> executed with errors: Bad status 401 (in scheduler.js:37)
Call Stack:
    at handleError (/usr/lib/node_modules/atlasboard/lib/scheduler.js:37:29)
    at jobCallback (/usr/lib/node_modules/atlasboard/lib/scheduler.js:95:9)
    at /home/aca/mydashboard/packages/SonarQube/jobs/qg-filter/qg-filter.js:53:17
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```
I think it has to de with my rootURL or with the place the package shoukd be in to.

**Comment by erichirlemann** [comment]
Hi,
The status code 401 is rather an authentication issue. Are you able to connect manually with the credential you have in your `globalAuth` file
